In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

In [2]:
# quantidade de pacientes
n_pacientes = 100

pacientes = pd.DataFrame({
    'id_paciente': range(1, n_pacientes + 1),
    'nome': [f'Paciente_{i}' for i in range(1, n_pacientes + 1)],
    'idade': np.random.randint(0, 90, n_pacientes),
    'sexo': np.random.choice(['M', 'F'], n_pacientes)
})

pacientes.head()

   id_paciente        nome  idade sexo
0            1  Paciente_1     36    F
1            2  Paciente_2     48    M
2            3  Paciente_3     85    M
3            4  Paciente_4     35    F
4            5  Paciente_5     45    M

In [3]:
n_internacoes = 200

setores = ['UTI', 'Emergência', 'Enfermaria', 'Centro Cirúrgico']

internacoes = []

for i in range(1, n_internacoes + 1):
    paciente_id = random.randint(1, n_pacientes)
    
    data_entrada = datetime(2024, 1, 1) + timedelta(days=random.randint(0, 365))
    tempo_internado = random.randint(1, 15)
    data_saida = data_entrada + timedelta(days=tempo_internado)

    setor = random.choice(setores)

    internacoes.append([
        i, paciente_id, data_entrada, data_saida, setor
    ])

internacoes = pd.DataFrame(internacoes, columns=[
    'id_internacao', 'id_paciente', 'data_entrada', 'data_saida', 'setor'
])

internacoes.head()

   id_internacao  id_paciente data_entrada data_saida             setor
0              1           65   2024-09-20 2024-09-29  Centro Cirúrgico
1              2           68   2024-05-12 2024-05-13        Emergência
2              3           90   2024-07-21 2024-07-27        Enfermaria
3              4           21   2024-05-16 2024-05-19        Enfermaria
4              5            5   2024-08-22 2024-08-23        Enfermaria

In [4]:
procedimentos = pd.DataFrame({
    'id_procedimento': [1,2,3,4,5],
    'descricao': [
        'Consulta médica',
        'Exame de sangue',
        'Raio-X',
        'Cirurgia',
        'Diária hospitalar'
    ],
    'custo_unitario': [150, 80, 200, 5000, 300]
})

procedimentos

   id_procedimento          descricao  custo_unitario
0                1    Consulta médica             150
1                2    Exame de sangue              80
2                3             Raio-X             200
3                4           Cirurgia            5000
4                5  Diária hospitalar             300

In [5]:
faturamento = []

for _, row in internacoes.iterrows():
    qtd_procedimentos = random.randint(1, 5)
    
    for _ in range(qtd_procedimentos):
        proc = procedimentos.sample(1).iloc[0]
        
        quantidade = random.randint(1, 3)
        custo_total = quantidade * proc['custo_unitario']
        
        faturamento.append([
            row['id_internacao'],
            proc['id_procedimento'],
            quantidade,
            custo_total
        ])

faturamento = pd.DataFrame(faturamento, columns=[
    'id_internacao', 'id_procedimento', 'quantidade', 'custo_total'
])

faturamento.head()

   id_internacao  id_procedimento  quantidade  custo_total
0              1                2           1           80
1              1                1           2          300
2              1                5           3          900
3              2                3           2          400
4              3                4           1         5000

In [6]:
pacientes.to_csv('data/raw/pacientes.csv', index=False)
internacoes.to_csv('data/raw/internacoes.csv', index=False)
procedimentos.to_csv('data/raw/procedimentos.csv', index=False)
faturamento.to_csv('data/raw/faturamento.csv', index=False)